_BASE_: [
  '../datasets/coco_detection_VEDAI.yml',
  '../runtime_vedai.yml',
  '_base_/optimizer_vedai.yml',
  '_base_/HrDETR_r50vd_1024.yml',
  '_base_/HrDETR_reader_1024.yml',
]

find_unused_parameters: True
log_iter: 200
